-- mod-version:3
local syntax = require "core.syntax"

syntax.add {
  name = "RPM Spec",
  files = { "%.spec$" },
  comment = "#",
  patterns = {
    -- common types --
    { pattern = "^#.*\n",                          type = "comment"  },
    { pattern = "[!<>|&%[%]=*()]",                   type = "operator" },
    -- int
    { pattern = "[%d]+%s",                         type = "number"   }, 
    -- hex
    { pattern = "%x%x%x%x%x+",                     type = "number"   }, 
    -- version
    { pattern = "%s[%d%.]+",                       type = "string"   }, 
    { pattern = { '"', '"', '\\' },                type = "string"   },
    -- inline commands, no quotes
    { pattern = "^\\$",                            type = "normal"   },

    -- language specific types --
    -- normal and predefined  macros
    { pattern = "%%{[%l_]+%}",                     type = "function", "symbol" }, 

    -- conditional macro with expansion
    { 
      pattern = "%%%{[%?%!]+[%l_]+%:[%g%s]+[%}]+",      
      type = "function" 
    },

    -- arch keywords
    { pattern = "[%l%d_]+[%.\\%d]+",                type = "symbol"   }, 
    -- all caps keywords
    { pattern = "%u%u[%u_]+",                       type = "symbol"   },
    -- commands 
    { pattern = "^%%[%l_]+",                        type = "symbol"   },
    -- package tags
    { pattern = "^[%u%l]+%:",                       type = "symbol"   },
    
    -- hard defined patterns
    { pattern = "^Source[%d]+%:",                   type = "keyword2" },
    { pattern = "^Patch[%d]+%:",                    type = "keyword2" },
    -- url's
    { pattern = "http[s]?://[%g]*",                 type = "string"   }, 
  };
    
  symbols = {
        -- commands "function" 
        ["%prep"]                          = "function", 
        ["%build"]                         = "function",
        ["%pre"]                           = "function",
        ["%preun"]                         = "function",
        ["%install"]                       = "function",
        ["%post"]                          = "function",
        ["%postun"]                        = "function",
        ["%clean"]                         = "function",
        ["%files"]                         = "function",
        ["%trigger"]                       = "function",
        ["%triggerin"]                     = "function",
        ["%triggerun"]                     = "function",
        ["%triggerpostun"]                 = "function",
        ["%verifyscript"]                  = "function",
        ["%check"]                         = "function",
        ["%pretrans"]                      = "function",
        ["%posttrans"]                     = "function",
        ["%filetriggerin"]                 = "function",
        ["%filetriggerun"]                 = "function",
        ["%filetriggerpostun"]             = "function",
        ["%transfiletriggerin"]            = "function",
        ["%transfiletriggerun"]            = "function",
        ["%transfiletriggerpostun"]        = "function",
        ["%generate_buildrequires"]        = "function",

        -- predefined commands "operator"
        ["%if"]                            = "operator",
        ["%else"]                          = "operator",
        ["%endif"]                         = "operator",
        ["%define"]                        = "operator",
        ["%description"]                   = "operator",
        ["%undefine"]                      = "operator",
        ["%package"]                       = "operator",
        ["%changelog"]                     = "operator",

        -- architectures "keyword"
        ["aarch64"]                        = "keyword",
        ["alpha"]                          = "keyword",
        ["alphaev5"]                       = "keyword",
        ["alphaev56"]                      = "keyword",
        ["alphaev6"]                       = "keyword",
        ["alphaev67"]                      = "keyword",
        ["alphapca56"]                     = "keyword",
        ["amd64"]                          = "keyword",
        ["armv3l"]                         = "keyword",
        ["armv4b"]                         = "keyword",
        ["armv4l"]                         = "keyword",
        ["armv4tl"]                        = "keyword",
        ["armv5tejl"]                      = "keyword",
        ["armv5tel"]                       = "keyword",
        ["armv5tl"]                        = "keyword",
        ["armv6hl"]                        = "keyword",
        ["armv6l"]                         = "keyword",
        ["armv7hl"]                        = "keyword",
        ["armv7hnl"]                       = "keyword",
        ["armv7l"]                         = "keyword",
        ["atariclone"]                     = "keyword",
        ["atarist"]                        = "keyword",
        ["atariste"]                       = "keyword",
        ["ataritt"]                        = "keyword",
        ["athlon"]                         = "keyword",
        ["em64t"]                          = "keyword",
        ["falcon"]                         = "keyword",
        ["fat"]                            = "keyword",
        ["geode"]                          = "keyword",
        ["hades"]                          = "keyword",
        ["hppa1\\.0"]                      = "keyword",
        ["hppa1\\.1"]                      = "keyword",
        ["hppa1\\.2"]                      = "keyword",
        ["hppa2\\.0"]                      = "keyword",
        ["i370"]                           = "keyword",
        ["i386"]                           = "keyword",
        ["i486"]                           = "keyword",
        ["i586"]                           = "keyword",
        ["i686"]                           = "keyword",
        ["ia32e"]                          = "keyword",
        ["ia64"]                           = "keyword",
        ["IP"]                             = "keyword",
        ["m68k"]                           = "keyword",
        ["m68kmint"]                       = "keyword",
        ["milan"]                          = "keyword",
        ["mips"]                           = "keyword",
        ["mips64"]                         = "keyword",
        ["mips64el"]                       = "keyword",
        ["mips64r6"]                       = "keyword",
        ["mips64r6el"]                     = "keyword",
        ["mipsel"]                         = "keyword",
        ["mipsr6"]                         = "keyword",
        ["mipsr6el"]                       = "keyword",
        ["noarch"]                         = "keyword",
        ["osfmach3_i386"]                  = "keyword",
        ["osfmach3_i486"]                  = "keyword",
        ["osfmach3_i586"]                  = "keyword",
        ["osfmach3_i686"]                  = "keyword",
        ["osfmach3_ppc"]                   = "keyword",
        ["parisc"]                         = "keyword",
        ["pentium3"]                       = "keyword",
        ["pentium4"]                       = "keyword",
        ["powerpc"]                        = "keyword",
        ["powerppc"]                       = "keyword",
        ["ppc"]                            = "keyword",
        ["ppc32dy4"]                       = "keyword",
        ["ppc64"]                          = "keyword",
        ["ppc64iseries"]                   = "keyword",
        ["ppc64le"]                        = "keyword",
        ["ppc64p7"]                        = "keyword",
        ["ppc64pseries"]                   = "keyword",
        ["ppc8260"]                        = "keyword",
        ["ppc8560"]                        = "keyword",
        ["ppciseries"]                     = "keyword",
        ["ppcpseries"]                     = "keyword",
        ["riscv"]                          = "keyword",
        ["riscv64"]                        = "keyword",
        ["rs6000"]                         = "keyword",
        ["s390"]                           = "keyword",
        ["s390x"]                          = "keyword",
        ["sh"]                             = "keyword",
        ["sh3"]                            = "keyword",
        ["sh4"]                            = "keyword",
        ["sh4a"]                           = "keyword",
        ["sparc"]                          = "keyword",
        ["sparc64"]                        = "keyword",
        ["sparc64v"]                       = "keyword",
        ["sparcv8"]                        = "keyword",
        ["sparcv9"]                        = "keyword",
        ["sparcv9v"]                       = "keyword",
        ["sun4"]                           = "keyword",
        ["sun4c"]                          = "keyword",
        ["sun4d"]                          = "keyword",
        ["sun4m"]                          = "keyword",
        ["sun4u"]                          = "keyword",
        ["x86_64"]                         = "keyword",
        ["xtensa"]                         = "keyword",

-- os name "keyword"
        ["AIX"]                            = "keyword",
        ["AmigaOS"]                        = "keyword",
        ["bsdi"]                           = "keyword",
        ["bsdi4\\.0"]                      = "keyword",
        ["BSD_OS"]                         = "keyword",
        ["cygwin32"]                       = "keyword",
        ["CYGWIN32_95"]                    = "keyword",
        ["CYGWIN32_NT"]                    = "keyword",
        ["darwin"]                         = "keyword",
        ["Darwin"]                         = "keyword",
        ["FreeBSD"]                        = "keyword",
        ["FreeMiNT"]                       = "keyword",
        ["HP-UX"]                          = "keyword",
        ["hpux10"]                         = "keyword",
        ["hpux10\\.00"]                    = "keyword",
        ["hpux10\\.01"]                    = "keyword",
        ["hpux10\\.10"]                    = "keyword",
        ["hpux10\\.20"]                    = "keyword",
        ["hpux10\\.30"]                    = "keyword",
        ["hpux11\\.00"]                    = "keyword",
        ["hpux9\\.04"]                     = "keyword",
        ["hpux9\\.05"]                     = "keyword",
        ["hpux9\\.07"]                     = "keyword",
        ["Irix"]                           = "keyword",
        ["IRIX"]                           = "keyword",
        ["Irix64"]                         = "keyword",
        ["IRIX64"]                         = "keyword",
        ["Linux"]                          = "keyword",
        ["Linux\\/390"]                    = "keyword",
        ["Linux\\/ESA"]                    = "keyword",
        ["machten"]                        = "keyword",
        ["macosx"]                         = "keyword",
        ["MacOSX"]                         = "keyword",
        ["mint"]                           = "keyword",
        ["MiNT"]                           = "keyword",
        ["MP_RAS"]                         = "keyword",
        ["ncr-sysv4\\.2"]                  = "keyword",
        ["ncr-sysv4\\.3"]                  = "keyword",
        ["NextStep"]                       = "keyword",
        ["NEXTSTEP"]                       = "keyword",
        ["OS\\/390"]                       = "keyword",
        ["osf1"]                           = "keyword",
        ["OSF1"]                           = "keyword",
        ["osf3\\.2"]                       = "keyword",
        ["osf4\\.0"]                       = "keyword",
        ["SCO_SV"]                         = "keyword",
        ["SCO_SV3\\.2v5\\.0\\.2"]          = "keyword",
        ["solaris"]                        = "keyword",
        ["solaris2\\.3"]                   = "keyword",
        ["solaris2\\.4"]                   = "keyword",
        ["solaris2\\.5"]                   = "keyword",
        ["solaris2\\.6"]                   = "keyword",
        ["solaris2\\.7"]                   = "keyword",
        ["SunOS"]                          = "keyword",
        ["SunOS4"]                         = "keyword",
        ["SunOS5"]                         = "keyword",
        ["TOS"]                            = "keyword",
        ["UNIX_SV"]                        = "keyword",
        ["VM\\/ESA"]                       = "keyword",

-- arch conditional names "operator"
        ["%ifarch"]                        = "operator",
        ["%ifnarch"]                       = "operator",

-- os conditional names "operator"
        ["%ifos"]                          = "operator",
        ["%ifnos"]                         = "operator",

-- package information "keyword2"
        ["Name:"]                          = "keyword2",
        ["Version:"]                       = "keyword2",
        ["Release:"]                       = "keyword2",
        ["Url:"]                           = "keyword2",
        ["URL:"]                           = "keyword2",
        ["Copyright:"]                     = "keyword2",
        ["License:"]                       = "keyword2",
        ["Summary:"]                       = "keyword2",
        ["Distribution:"]                  = "keyword2",
        ["Vendor:"]                        = "keyword2",
        ["Packager:"]                      = "keyword2",
        ["Group:"]                         = "keyword2",
        ["BuildRoot:"]                     = "keyword2",
        ["Prefix:"]                        = "keyword2",
        ["ExclusiveOs:"]                   = "keyword2",
        ["ExcludeOs:"]                     = "keyword2",
        ["BuildArch:"]                     = "keyword2",
        ["BuildArchitectures:"]            = "keyword2",
        ["ExclusiveArch:"]                 = "keyword2",
        ["ExcludeArch:"]                   = "keyword2",
        ["Epoch:"]                         = "keyword2",
        ["Serial:"]                        = "keyword2",
        ["Nosource:"]                      = "keyword2",
        ["Nopatch:"]                       = "keyword2",
        ["AutoReq:"]                       = "keyword2",
        ["AutoProv:"]                      = "keyword2",
        ["AutoReqProv:"]                   = "keyword2",
        ["Icon:"]                          = "keyword2",

-- build requirements "keyword2"
        ["Conflicts:"]                     = "keyword2",
        ["Obsoletes:"]                     = "keyword2",
        ["Provides:"]                      = "keyword2",
        ["Requires:"]                      = "keyword2",
        ["Enhances:"]                      = "keyword2",
        ["Suggests:"]                      = "keyword2",
        ["BuildConflicts:"]                = "keyword2",
        ["BuildRequires:"]                 = "keyword2",
        ["Recommends:"]                    = "keyword2",
        ["PreReq:"]                        = "keyword2",
        ["BuildPreReq:"]                   = "keyword2",
        ["Supplements:"]                   = "keyword2",
        ["OrderWithRequires:"]             = "keyword2",
        ["RemovePathPostfixes:"]           = "keyword2",

-- helper macros "keyword"
        ["%autopatch"]                     = "keyword2",
        ["%autosetup"]                     = "keyword2",
        ["%doc"]                           = "keyword2",
        ["%cmake"]                         = "keyword2",
        ["%license"]                       = "keyword2",
        ["%make"]                          = "keyword2",
        ["%make_build"]                    = "keyword2",
        ["%make_install"]                  = "keyword2",
        ["%meson"]                         = "keyword2",
        ["%ninja_build"]                   = "keyword2",
        ["%ninja_install"]                 = "keyword2",
        ["%setup"]                         = "keyword2",

-- autoconf macros and analogues "keyword"
        ["%{_prefix}"]                     = "keyword",
        ["%{_bindir}"]                     = "keyword",
        ["%{_sbindir}"]                    = "keyword",
        ["%{_libexecdir}"]                 = "keyword",
        ["%{_datadir}"]                    = "keyword",
        ["%{_sysconfdir}"]                 = "keyword",
        ["%{_sharedstatedir}"]             = "keyword",
        ["%{_localstatedir}"]              = "keyword",
        ["%{_libdir}"]                     = "keyword",
        ["%{_includedir}"]                 = "keyword",
        ["%{_docdir}"]                     = "keyword",
        ["%{_mandir}"]                     = "keyword",
        ["%{_infodir}"]                    = "keyword",
        ["%{_oldincludedir}"]              = "keyword",

-- per sh language plugin "keyword"
        ["break"]                          = "keyword",
        ["case"]                           = "keyword",
        ["continue"]                       = "keyword",
        ["do"]                             = "keyword",
        ["done"]                           = "keyword",
        ["elif"]                           = "keyword",
        ["else"]                           = "keyword",
        ["esac"]                           = "keyword",
        ["fi"]                             = "keyword",
        ["for"]                            = "keyword",
        ["function"]                       = "keyword",
        ["if"]                             = "keyword",
        ["in"]                             = "keyword",
        ["return"]                         = "keyword",
        ["select"]                         = "keyword",
        ["then"]                           = "keyword",
        ["until"]                          = "keyword",
        ["while"]                          = "keyword"
  },
}

