-- mod-version:3
local syntax = require "core.syntax"

syntax.add {
  name = "RPM Spec",
  files = { "%.spec$" },
  comment = "#",
  patterns = {
    { pattern = "#.*\n",                         type = "comment"  },
    { pattern = "%s[%d]+%s",                     type = "number"   }, -- int
    { pattern = "^%x%x+$",                       type = "number"   }, -- hex
    { pattern = "%s[%d%.]+",                     type = "string"   }, -- version
    { pattern = { '"', '"', '\\' },              type = "string"   },
    { pattern = "%%{[%w_]*%}",                   type = "function" },
    { pattern = "[!<>|&%[%]=*]",                 type = "operator" },
    { pattern = "%%[%l]*%s",                     type = "keyword" },
    { pattern = "%%[%l_]*",                      type = "function" },
  },
  symbols = {
    -- commands
    ["%prep"]                     =    "keyword",
    ["%build"]                    =    "keyword",
    ["%pre"]                      =    "keyword",
    ["%preun"]                    =    "keyword",
    ["%install"]                  =    "keyword",
    ["%post"]                     =    "keyword",
    ["%postun"]                   =    "keyword",
    ["%clean"]                    =    "keyword",
    ["%files"]                    =    "keyword",
    ["%trigger"]                  =    "keyword",
    ["%triggerin"]                =    "keyword",
    ["%triggerun"]                =    "keyword",
    ["%triggerpostun"]            =    "keyword",
    ["%verifyscript"]             =    "keyword",
    ["%check"]                    =    "keyword",
    ["%pretrans"]                 =    "keyword",
    ["%posttrans"]                =    "keyword",
    ["%filetriggerin"]            =    "keyword",
    ["%filetriggerun"]            =    "keyword",
    ["%filetriggerpostun"]        =    "keyword",
    ["%transfiletriggerin"]       =    "keyword",
    ["%transfiletriggerun"]       =    "keyword",
    ["%transfiletriggerpostun"]   =    "keyword",
    ["%generate_buildrequires"]   =    "keyword",

    -- architectures
    ["aarch64"]                  =    "keyword2",
    ["alpha"]                    =    "keyword2",
    ["alphaev5"]                 =    "keyword2",
    ["alphaev56"]                =    "keyword2",
    ["alphaev6"]                 =    "keyword2",
    ["alphaev67"]                =    "keyword2",
    ["alphapca56"]               =    "keyword2",
    ["amd64"]                    =    "keyword2",
    ["armv31"]                   =    "keyword2",
    ["armv4b"]                   =    "keyword2",
    ["armv4l"]                   =    "keyword2",
    ["armv4tl"]                  =    "keyword2",
    ["armv5tejl"]                =    "keyword2",
    ["armv5tel"]                 =    "keyword2",
    ["armv5tl"]                  =    "keyword2",
    ["armv6hl"]                  =    "keyword2",
    ["armv6l"]                   =    "keyword2",
    ["armv7hl"]                  =    "keyword2",
    ["armv7hnl"]                 =    "keyword2",
    ["armv7l"]                   =    "keyword2",
    ["atariclone"]               =    "keyword2",
    ["atarist"]                  =    "keyword2",
    ["atariste"]                 =    "keyword2",
    ["ataritt"]                  =    "keyword2",
    ["athlon"]                   =    "keyword2",
    ["em64t"]                    =    "keyword2",
    ["falcon"]                   =    "keyword2",
    ["fat"]                      =    "keyword2",
    ["geode"]                    =    "keyword2",
    ["hades"]                    =    "keyword2",
    ["hppa1\\.0"]                =    "keyword2",
    ["hppa1\\.1"]                =    "keyword2",
    ["hppa1\\.2"]                =    "keyword2",
    ["hppa2\\.0"]                =    "keyword2",
    ["i370"]                     =    "keyword2",
    ["i386"]                     =    "keyword2",
    ["i486"]                     =    "keyword2",
    ["i586"]                     =    "keyword2",
    ["i686"]                     =    "keyword2",
    ["ia32e"]                    =    "keyword2",
    ["ia64"]                     =    "keyword2",
    ["IP"]                       =    "keyword2",
    ["m68k"]                     =    "keyword2",
    ["m68kmint"]                 =    "keyword2",
    --|milan|mips|mips64|mips64el|mips64r6|mips64r6el|mipsel|mipsr6|mipsr6el|noarch|osfmach3_i386|osfmach3_i486|osfmach3_i586|osfmach3_i686|osfmach3_ppc|parisc|pentium3|pentium4|powerpc|powerppc|ppc|ppc32dy4|ppc64|ppc64iseries|ppc64le|ppc64p7|ppc64pseries|ppc8260|ppc8560|ppciseries|ppcpseries|riscv|riscv64|rs6000|s390|s390x|sh|sh3|sh4|sh4a|sparc|sparc64|sparc64v|sparcv8|sparcv9|sparcv9v|sun4|sun4c|sun4d|sun4m|sun4u|x86_64|xtensa
    
    --literals
    ["nil"]                =    "literal"
  },
}
