-- Author: Blackoutburst: https://github.com/Blackoutburst

-- mod-version:3
local syntax = require "core.syntax"

syntax.add {
  name    = "Slang",
  files   = { "%.slang$" },
  comment = "//",
  block_comment = { "/*", "*/" },

  patterns = {
    { pattern = "//.-\n",                                    type = "comment" },
    { pattern = { "/%*", "%*/" },                            type = "comment" },

    { pattern = "%[%s*[%a_][%w_%.]*%s*[%(%]]",               type = "keyword2" },
    { pattern = "%[%s*[%a_][%w_%.]*",                        type = "keyword2" },

    { pattern = "SV_[%u%d_]+",                               type = "keyword2" },

    { pattern = "#%s*[%a_][%w_]*",                           type = "keyword" },

    { pattern = { '"', '"', '\\' },                          type = "string" },
    { pattern = { "'", "'", '\\' },                          type = "string" },

    { pattern = "0[xX][%da-fA-F]+[uUlL]*",                   type = "number" },
    { pattern = "%d+%.%d*[eEfF]?[fFhHuUlL]*",                type = "number" },
    { pattern = "%.%d+[eEfF]?[fFhHuUlL]*",                   type = "number" },
    { pattern = "%d+[eEfF][%+%-]?%d+[fFhHuUlL]*",            type = "number" },
    { pattern = "%d+[fFhHuUlL]*",                            type = "number" },

    { pattern = "[%a_][%w_]*%f[(]",                          type = "function" },

    { pattern = "[%+%-%*/%^%%=<>!~|&%?:%.%[%]%(%)%{%}%;%,]", type = "operator" },

    { pattern = "[%a_][%w_]*",                               type = "symbol" },
  },

  symbols = {
    ["if"]                                   = "keyword",
    ["else"]                                 = "keyword",
    ["for"]                                  = "keyword",
    ["while"]                                = "keyword",
    ["do"]                                   = "keyword",
    ["switch"]                               = "keyword",
    ["case"]                                 = "keyword",
    ["default"]                              = "keyword",
    ["break"]                                = "keyword",
    ["continue"]                             = "keyword",
    ["return"]                               = "keyword",
    ["discard"]                              = "keyword",

    ["struct"]                               = "keyword",
    ["interface"]                            = "keyword",
    ["enum"]                                 = "keyword",
    ["class"]                                = "keyword",
    ["typedef"]                              = "keyword",
    ["typealias"]                            = "keyword",
    ["associatedtype"]                       = "keyword",
    ["extension"]                            = "keyword",
    ["namespace"]                            = "keyword",

    ["module"]                               = "keyword",
    ["import"]                               = "keyword",
    ["export"]                               = "keyword",
    ["implementing"]                         = "keyword",

    ["const"]                                = "keyword",
    ["constexpr"]                            = "keyword",
    ["static"]                               = "keyword",
    ["extern"]                               = "keyword",
    ["inline"]                               = "keyword",
    ["__generic"]                            = "keyword",
    ["let"]                                  = "keyword",
    ["var"]                                  = "keyword",
    ["property"]                             = "keyword",
    ["get"]                                  = "keyword",
    ["set"]                                  = "keyword",

    ["in"]                                   = "keyword",
    ["out"]                                  = "keyword",
    ["inout"]                                = "keyword",
    ["ref"]                                  = "keyword",
    ["uniform"]                              = "keyword",
    ["varying"]                              = "keyword",

    ["sizeof"]                               = "keyword",
    ["this"]                                 = "keyword",
    ["cbuffer"]                              = "keyword",
    ["tbuffer"]                              = "keyword",
    ["register"]                             = "keyword",
    ["packoffset"]                           = "keyword",

    ["void"]                                 = "keyword2",
    ["bool"]                                 = "keyword2",
    ["int"]                                  = "keyword2",
    ["uint"]                                 = "keyword2",
    ["float"]                                = "keyword2",
    ["double"]                               = "keyword2",
    ["half"]                                 = "keyword2",
    ["int8_t"]                               = "keyword2",
    ["int16_t"]                              = "keyword2",
    ["int32_t"]                              = "keyword2",
    ["int64_t"]                              = "keyword2",
    ["uint8_t"]                              = "keyword2",
    ["uint16_t"]                             = "keyword2",
    ["uint32_t"]                             = "keyword2",
    ["uint64_t"]                             = "keyword2",
    ["float16_t"]                            = "keyword2",
    ["float32_t"]                            = "keyword2",
    ["float64_t"]                            = "keyword2",

    ["bool2"]                                = "keyword2",
    ["bool3"]                                = "keyword2",
    ["bool4"]                                = "keyword2",
    ["int2"]                                 = "keyword2",
    ["int3"]                                 = "keyword2",
    ["int4"]                                 = "keyword2",
    ["uint2"]                                = "keyword2",
    ["uint3"]                                = "keyword2",
    ["uint4"]                                = "keyword2",
    ["float2"]                               = "keyword2",
    ["float3"]                               = "keyword2",
    ["float4"]                               = "keyword2",
    ["double2"]                              = "keyword2",
    ["double3"]                              = "keyword2",
    ["double4"]                              = "keyword2",
    ["half2"]                                = "keyword2",
    ["half3"]                                = "keyword2",
    ["half4"]                                = "keyword2",
    ["vector"]                               = "keyword2",

    ["float2x2"]                             = "keyword2",
    ["float2x3"]                             = "keyword2",
    ["float2x4"]                             = "keyword2",
    ["float3x2"]                             = "keyword2",
    ["float3x3"]                             = "keyword2",
    ["float3x4"]                             = "keyword2",
    ["float4x2"]                             = "keyword2",
    ["float4x3"]                             = "keyword2",
    ["float4x4"]                             = "keyword2",
    ["int2x2"]                               = "keyword2",
    ["int3x3"]                               = "keyword2",
    ["int4x4"]                               = "keyword2",
    ["double2x2"]                            = "keyword2",
    ["double3x3"]                            = "keyword2",
    ["double4x4"]                            = "keyword2",
    ["matrix"]                               = "keyword2",

    ["Texture1D"]                            = "keyword2",
    ["Texture2D"]                            = "keyword2",
    ["Texture3D"]                            = "keyword2",
    ["TextureCube"]                          = "keyword2",
    ["Texture1DArray"]                       = "keyword2",
    ["Texture2DArray"]                       = "keyword2",
    ["TextureCubeArray"]                     = "keyword2",
    ["Texture2DMS"]                          = "keyword2",
    ["Texture2DMSArray"]                     = "keyword2",
    ["RWTexture1D"]                          = "keyword2",
    ["RWTexture2D"]                          = "keyword2",
    ["RWTexture3D"]                          = "keyword2",
    ["RWTexture1DArray"]                     = "keyword2",
    ["RWTexture2DArray"]                     = "keyword2",
    ["Buffer"]                               = "keyword2",
    ["StructuredBuffer"]                     = "keyword2",
    ["ByteAddressBuffer"]                    = "keyword2",
    ["RWBuffer"]                             = "keyword2",
    ["RWStructuredBuffer"]                   = "keyword2",
    ["RWByteAddressBuffer"]                  = "keyword2",
    ["AppendStructuredBuffer"]               = "keyword2",
    ["ConsumeStructuredBuffer"]              = "keyword2",
    ["ConstantBuffer"]                       = "keyword2",
    ["ParameterBlock"]                       = "keyword2",
    ["RaytracingAccelerationStructure"]      = "keyword2",

    ["SamplerState"]                         = "keyword2",
    ["SamplerComparisonState"]               = "keyword2",

    ["true"]                                 = "literal",
    ["false"]                                = "literal",
    ["null"]                                 = "literal",

    ["abs"]                                  = "function",
    ["sign"]                                 = "function",
    ["floor"]                                = "function",
    ["ceil"]                                 = "function",
    ["round"]                                = "function",
    ["trunc"]                                = "function",
    ["frac"]                                 = "function",
    ["modf"]                                 = "function",
    ["fmod"]                                 = "function",
    ["sqrt"]                                 = "function",
    ["rsqrt"]                                = "function",
    ["pow"]                                  = "function",
    ["exp"]                                  = "function",
    ["exp2"]                                 = "function",
    ["log"]                                  = "function",
    ["log2"]                                 = "function",
    ["sin"]                                  = "function",
    ["cos"]                                  = "function",
    ["tan"]                                  = "function",
    ["asin"]                                 = "function",
    ["acos"]                                 = "function",
    ["atan"]                                 = "function",
    ["atan2"]                                = "function",
    ["sinh"]                                 = "function",
    ["cosh"]                                 = "function",
    ["tanh"]                                 = "function",
    ["degrees"]                              = "function",
    ["radians"]                              = "function",

    ["dot"]                                  = "function",
    ["cross"]                                = "function",
    ["normalize"]                            = "function",
    ["length"]                               = "function",
    ["distance"]                             = "function",
    ["mul"]                                  = "function",
    ["transpose"]                            = "function",
    ["determinant"]                          = "function",
    ["reflect"]                              = "function",
    ["refract"]                              = "function",
    ["faceforward"]                          = "function",

    ["min"]                                  = "function",
    ["max"]                                  = "function",
    ["clamp"]                                = "function",
    ["saturate"]                             = "function",
    ["lerp"]                                 = "function",
    ["smoothstep"]                           = "function",
    ["step"]                                 = "function",

    ["any"]                                  = "function",
    ["all"]                                  = "function",
    ["select"]                               = "function",

    ["asfloat"]                              = "function",
    ["asint"]                                = "function",
    ["asuint"]                               = "function",
    ["asdouble"]                             = "function",
    ["countbits"]                            = "function",
    ["firstbithigh"]                         = "function",
    ["firstbitlow"]                          = "function",
    ["reversebits"]                          = "function",

    ["ddx"]                                  = "function",
    ["ddy"]                                  = "function",
    ["ddx_coarse"]                           = "function",
    ["ddy_coarse"]                           = "function",
    ["ddx_fine"]                             = "function",
    ["ddy_fine"]                             = "function",
    ["fwidth"]                               = "function",

    ["InterlockedAdd"]                       = "function",
    ["InterlockedAnd"]                       = "function",
    ["InterlockedOr"]                        = "function",
    ["InterlockedXor"]                       = "function",
    ["InterlockedMin"]                       = "function",
    ["InterlockedMax"]                       = "function",
    ["InterlockedExchange"]                  = "function",
    ["InterlockedCompareExchange"]           = "function",

    ["AllMemoryBarrier"]                     = "function",
    ["AllMemoryBarrierWithGroupSync"]        = "function",
    ["DeviceMemoryBarrier"]                  = "function",
    ["DeviceMemoryBarrierWithGroupSync"]     = "function",
    ["GroupMemoryBarrier"]                   = "function",
    ["GroupMemoryBarrierWithGroupSync"]      = "function",

    ["WaveGetLaneCount"]                     = "function",
    ["WaveGetLaneIndex"]                     = "function",
    ["WaveIsFirstLane"]                      = "function",
    ["WaveReadLaneFirst"]                    = "function",
    ["WaveReadLaneAt"]                       = "function",
    ["WaveActiveAllTrue"]                    = "function",
    ["WaveActiveAnyTrue"]                    = "function",
    ["WaveActiveBallot"]                     = "function",
    ["WaveActiveSum"]                        = "function",
    ["WaveActiveProduct"]                    = "function",
    ["WaveActiveMin"]                        = "function",
    ["WaveActiveMax"]                        = "function",
    ["WaveActiveCountBits"]                  = "function",
    ["WavePrefixSum"]                        = "function",
    ["WavePrefixProduct"]                    = "function",
    ["WavePrefixCountBits"]                  = "function",
    ["QuadReadAcrossX"]                      = "function",
    ["QuadReadAcrossY"]                      = "function",
    ["QuadReadAcrossDiagonal"]               = "function",
    ["QuadReadLaneAt"]                       = "function",
  },
}
